# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = alembic

# template used to generate migration files
#file_template = %%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present.
# defaults to the current working directory.
prepend_sys_path = .

# If set, version_path_kind will determine how the version_path is
# constructed for new revisions. Only affects versions created
# after this line is set.  Valid values for version_path_kind are:
#   filename:  Use the revision number as the filename.  This is the
#              default for new revisions, as well as for backwards
#              compatibility with database-first migrations.
#   directory:  Create a new directory for each revision, using the
#              revision number as the directory name.
version_path_kind = dirname

# The string literal to render when generating a revision
# label indicates that the revision is the base for the following
# chain.
#base_label = base

# Set to 'true' to run the environment during the
# revision command.
#revision_environment = false

# Set to 'true' to allow subdirectories as version_path
#allow_subdirectories = false

# @param: cyclical_pattern_consolidation_templates
# A list of jinja2 template strings that will be rendered with
# the same context as the file_template, to create multiple files
# per revision when using cyclical pattern consolidation.
#cyclical_pattern_consolidation_templates = []

# The output encoding when revision files are written
#output_encoding = utf-8

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
args = ()
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S